site_name: Pr1m3d Team Blog
site_url: "https://pr1m3dctf.github.io/blog"
site_description: "Pr1m3d Team Blog"
site_author: "Pr1m3d"
repo_name: 'Pr1m3dCTF/blog'
edit_uri: 'blob/master/docs/'
repo_url: 'https://github.com/Pr1m3dCTF/blog'


theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: mydark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: mylight
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


  features:
    - navigation.tabs  # Enables top navigation
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigating.sections
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.select
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true

  
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - glightbox
  - search
  # - git-authors
  - tags:
      title: Pr1m3d Team Blog
      description: Welcome To Pr1m3d Team Blogs
      # image: docs/favicon.png
  # - social:
  #     cards: true
  #     # cards_layout: default


nav:
  - Home: .
  - Research: Researches/
  - Blog Post: 
    - Blog-Posts/index.md
    - Android Stack Overflow Exploitation with Frida: Blog-Posts/Android-Stack-Overflow-Exploitation-with-Frida.md
    - Analyzing MSFVenom Android Payload: Blog-Posts/Msfvenom-Android-Malware-Analysis.md
    - HTB Busqueda Machine Writeup: Blog-Posts/HTB-Busqueda-Machine-Writeup.md
    - PWN - Stack binary exploiting Writeup: Blog-Posts/PWN-Stack-binary-exploiting-Writeup.md
  - CVE: CVE/
  - CTF:
    - CTF/index.md
    - writeups:
      - 2023:
        - Cyber Apocalypse 2023: 
          - crypto: 
            - inside the matrix: CTF/writeups/2023/cyber-apocalypse-2023/crypto/inside_the_matrix.md
            - multipage recyclings: CTF/writeups/2023/cyber-apocalypse-2023/crypto/multipage_recyclings.md
            - perfect synchronization: CTF/writeups/2023/cyber-apocalypse-2023/crypto/perfect_synchronization.md
            - small steps: CTF/writeups/2023/cyber-apocalypse-2023/crypto/small_steps.md
          - blockchain:
            - navigating the unknown: CTF/writeups/2023/cyber-apocalypse-2023/blockchain/navigating_the_unknown.md
            - shooting 101: CTF/writeups/2023/cyber-apocalypse-2023/blockchain/shooting_101.md
          - web:
            - passman: CTF/writeups/2023/cyber-apocalypse-2023/web/passman.md
          - hardware: 
            - hm74: CTF/writeups/2023/cyber-apocalypse-2023/hardware/hm74.md
          - forensics:
            - packet cyclone: CTF/writeups/2023/cyber-apocalypse-2023/forensics/packet_cyclone.md
      - 2024:
        - Snapp CTF 2024:
          - CTF/writeups/2024/Snapp-ctf-2024/index.md
          - crypto: 
            - Cryptos: CTF/writeups/2024/Snapp-ctf-2024/crypto/Cryptos.md
            - Bombastic: CTF/writeups/2024/Snapp-ctf-2024/crypto/Bombastic.md
            - Blex: CTF/writeups/2024/Snapp-ctf-2024/crypto/Blex.md
            - Grail: CTF/writeups/2024/Snapp-ctf-2024/crypto/Grail.md
          - pwn:
            - Snapp admin: CTF/writeups/2024/Snapp-ctf-2024/pwn/snapp_admin.md
            - Snapp shell: CTF/writeups/2024/Snapp-ctf-2024/pwn/snapp_shell.md
          - rev:
            - Visits: CTF/writeups/2024/Snapp-ctf-2024/rev/visits.md
            - TurnOB: CTF/writeups/2024/Snapp-ctf-2024/rev/turnob.md
            - Blink: CTF/writeups/2024/Snapp-ctf-2024/rev/blink.md
          - web:
            - Snapp cat: CTF/writeups/2024/Snapp-ctf-2024/web/snapp_cat.md
            - Snapp fal: CTF/writeups/2024/Snapp-ctf-2024/web/snapp_fal.md
            - welcome: CTF/writeups/2024/Snapp-ctf-2024/web/welcome.md
          - forensics:
            - Snapp Report: CTF/writeups/2024/Snapp-ctf-2024/forensics/snapp_report.md
          - osint:
            - Snapp Records: CTF/writeups/2024/Snapp-ctf-2024/osint/snapp_records.md
            - Snapp Bounties: CTF/writeups/2024/Snapp-ctf-2024/osint/snapp_bounties.md
            - Snapp Customers: CTF/writeups/2024/Snapp-ctf-2024/osint/snapp_customers.md
            - Snapp Saving: CTF/writeups/2024/Snapp-ctf-2024/osint/snapp_saving.md
        - Cyber Apocalypse 2024:
          - crypto:
            - Permuted: CTF/writeups/2024/Cyber-Apocalypse-2024/crypto/permuted.md
          - blockchain:
            - Lucky Facucet: CTF/writeups/2024/Cyber-Apocalypse-2024/blockchain/luckyfaucet.md
            - Russian Roulette: CTF/writeups/2024/Cyber-Apocalypse-2024/blockchain/russianroulette.md
            - Ledger Heist: CTF/writeups/2024/Cyber-Apocalypse-2024/blockchain/ledgerheist.md
        - Just CTF 2024:
          - blockchain: CTF/writeups/2024/JustCTF2024/blockchain/blockchains.md

  - Contact Us: Contact-Us/
  - About Us: About-Us/



extra_css:
  - assets/css/extra.css


# extra:
#   git_authors:
#     exclude_emails: # List of emails to exclude from the authorship info
#       - "noreply@example.com"
#     include_coauthors: true # Include co-authors from commits